SUCESS = "Success"
NO_FACES_FOUND = "No Faces Found"
ERROR_PROCESSING_IMAGE = "Error Processing Image"
NO_BASELINE_IMAGE = "No Baseline Image"
UNKNOWN_PERSON = "Unknown Person"
MULTIPLE_FACES = "Multiple Faces"
KNOWN_MULTIPLE_FACES = "Known Multiple Faces"
PROCESSING = "Processing"